#ifndef QPXMLHELPER_GLOBAL_H
#define QPXMLHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPXMLHELPER_LIBRARY)
#  define QPXMLHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPXMLHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPXMLHELPER_GLOBAL_H
