#ifndef ERRORHANDLE_GLOBAL_H
#define ERRORHANDLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ERRORHANDLE_LIBRARY)
#  define ERRORHANDLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ERRORHANDLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ERRORHANDLE_GLOBAL_H
