#ifndef QPMESSAGEBOX_GLOBAL_H
#define QPMESSAGEBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPMESSAGEBOX_LIBRARY)
#  define QPMESSAGEBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPMESSAGEBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPMESSAGEBOX_GLOBAL_H
