#ifndef QPRIVATESQLHELPER_GLOBAL_H
#define QPRIVATESQLHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPRIVATESQLHELPER_LIBRARY)
#  define QPRIVATESQLHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPRIVATESQLHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPRIVATESQLHELPER_GLOBAL_H
