#ifndef QPUICONTROL_GLOBAL_H
#define QPUICONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPUICONTROL_LIBRARY)
#  define QPUICONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPUICONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPUICONTROL_GLOBAL_H
