#ifndef QPMAINFRAME_GLOBAL_H
#define QPMAINFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPMAINFRAME_LIBRARY)
#  define QPMAINFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPMAINFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPMAINFRAME_GLOBAL_H
